### ISSUE TITLE
[FR]open file browser for document root

### ISSUE THREAD

**Issue by fazlerabbi37** [mvbasov/lWS#1]
When we click on document root to select the document root for the web server, now an input box opens containing the file path where we I have to put the full path of the directory where we want our document root to be. It would make the process much easier if the file browser opened upon clicking document root and one could choose a directory from the file browser and it would be set as the document root for the web server. Thanks in advance!

**Comment by mvbasov** [comment]
This feature already implemented. Install [OI File Manager](https://play.google.com/store/apps/details?id=org.openintents.filemanager&hl=en_US) and enable it on settings screen.

**Comment by fazlerabbi37** [comment]
shouldn't that be enabled for all file managet instead of specific one?

**Comment by mvbasov** [comment]
My attempts to find way to 'pick directory' using another (closed source) file managers (X-Plore, Total Commander, e.t.c) had no success.
