### ISSUE TITLE
Allow webserver to be accessed only from localhost

### ISSUE THREAD

**Issue by Elettrotecnica** [mvbasov/lWS#10]
Hi and thanks a lot for this very nice software.

I understand there is currently no chance to prevent external clients from accessing my server. This would be very useful to implement local web applications that are not meant to be shared with the public.

Would it be possible to have a setting so that the server is only accessible via localhost?

Thanks again and all the best

**Comment by mvbasov** [comment]
Server accesable only via localhost in case of no any external interface is up (like aeropline mode)

**Comment by mvbasov** [comment]
Server accesable only via localhost in case of no any external interface is up (like aeropline mode)
