### ISSUE TITLE
Autostart 

### ISSUE THREAD

**Issue by stokito** [mvbasov/lWS#11]
I enabled the IWS for auto load on AndroidTV but I still have to manually press the Start button.
It would be great if IWS is automatically started when all is loaded

**Comment by mvbasov** [comment]
This may lead many security issues. Start process for this server need to be as manual as possible.

**Comment by stokito** [comment]
But actually you may just add a checkbox Start and save the state. On next load IWS may see if the server was started but not turned off then start it again.
