### ISSUE TITLE
Option to serve locally

### ISSUE THREAD

**Issue by Scrumplex** [mvbasov/lWS#3]
It should be possible to serve the content locally and not on wifi, so it can be accessed without any network connection.

**Comment by mvbasov** [comment]
What do you mean "without any network connection"? Aeroplane mode?
I am not sure is local (127.0.0.1) interface available in this mode. Need to check.
Operation on WiFi and Tethering mode only enabled for security reason. I don't want to expose device content on cellular network.

**Comment by Scrumplex** [comment]
I basically want it to have it listen on 127.0.0.1, as I want to serve something only on the device itself. So neither WiFi nor tethering should be required.

**Comment by mvbasov** [comment]
Done in v06.01.00b
